/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flightschedulerdbsiddharthduttasvd5571;

import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Sid
 */
public class FlightScheduler extends javax.swing.JFrame {

    /**
     * Creates new form FlightScheduler
     */
    public FlightScheduler() throws SQLException {
        initComponents();
        updatePassengerComboBoxes();
        updateFlightComboBoxes();
        updateDayComboBoxes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        enterCustomerNameLabel = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        addCustomerButton = new javax.swing.JButton();
        addCustomerStatusLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bookCustomerLabel = new javax.swing.JLabel();
        bookDayLabel = new javax.swing.JLabel();
        bookFlightLabel = new javax.swing.JLabel();
        bookDayComboBox = new javax.swing.JComboBox<>();
        bookCustomerComboBox = new javax.swing.JComboBox<>();
        bookFlightComboBox = new javax.swing.JComboBox<>();
        bookButton = new javax.swing.JButton();
        bookCustomerStatusLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bookingStatusFlightLabel = new javax.swing.JLabel();
        bookingStatusDayLabel = new javax.swing.JLabel();
        bookingStatusFlightComboBox = new javax.swing.JComboBox<>();
        bookingStatusDayComboBox = new javax.swing.JComboBox<>();
        bookingStatusFindButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        customersBookedList = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        waitlistStatusDayLabel = new javax.swing.JLabel();
        waitlistStatusDayComboBox = new javax.swing.JComboBox<>();
        waitlistStatusFindButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        waitlistStatusCustomersList = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        addFlightNameLabel = new javax.swing.JLabel();
        addFlightSeatsLabel = new javax.swing.JLabel();
        addFlightNameTextField = new javax.swing.JTextField();
        addFlightSeatsTextField = new javax.swing.JTextField();
        addFlightButton = new javax.swing.JButton();
        addFlightStatusLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        cancelCustomerNameLabel = new javax.swing.JLabel();
        cancelCustomerDayLabel = new javax.swing.JLabel();
        cancelCustomerNameComboBox = new javax.swing.JComboBox<>();
        cancelCustomerDayComboBox = new javax.swing.JComboBox<>();
        cancelCustomerButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        addDayLabel = new javax.swing.JLabel();
        addDateSpinner = new javax.swing.JSpinner();
        addDateButton = new javax.swing.JButton();
        addDayStatusLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        customerStatusLabel = new javax.swing.JLabel();
        customerStausComboBox = new javax.swing.JComboBox<>();
        customerStatusButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerStausList1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        customerStausList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        dropFlightLabel = new javax.swing.JLabel();
        dropFlightComboBox = new javax.swing.JComboBox<>();
        dropFlightButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setForeground(new java.awt.Color(153, 255, 255));

        enterCustomerNameLabel.setText("Enter Passenger Name:");

        addCustomerButton.setText("Add");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        addCustomerStatusLabel.setText("Status:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCustomerStatusLabel)
                    .addComponent(addCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(enterCustomerNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(260, 260, 260))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterCustomerNameLabel)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(addCustomerButton)
                .addGap(54, 54, 54)
                .addComponent(addCustomerStatusLabel)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Customer", jPanel1);

        bookCustomerLabel.setText("Customer:");

        bookDayLabel.setText("Day:");

        bookFlightLabel.setText("Flight:");

        bookDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----select----" }));

        bookCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----select----" }));

        bookFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----select----" }));

        bookButton.setText("Book");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });

        bookCustomerStatusLabel.setText("Status:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookCustomerStatusLabel)
                    .addComponent(bookDayLabel)
                    .addComponent(bookCustomerLabel)
                    .addComponent(bookFlightLabel))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 401, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookCustomerLabel)
                    .addComponent(bookCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookDayLabel)
                    .addComponent(bookDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookFlightLabel)
                    .addComponent(bookFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(bookButton)
                .addGap(18, 18, 18)
                .addComponent(bookCustomerStatusLabel)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Book", jPanel2);

        bookingStatusFlightLabel.setText("Flight:");

        bookingStatusDayLabel.setText("Day:");

        bookingStatusFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----select----" }));

        bookingStatusDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----select----" }));

        bookingStatusFindButton.setText("Find");
        bookingStatusFindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingStatusFindButtonActionPerformed(evt);
            }
        });

        customersBookedList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Customers Booked:" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(customersBookedList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bookingStatusFlightLabel)
                            .addComponent(bookingStatusDayLabel))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookingStatusFlightComboBox, 0, 225, Short.MAX_VALUE)
                            .addComponent(bookingStatusDayComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(bookingStatusFindButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookingStatusFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookingStatusFlightLabel))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookingStatusDayLabel)
                            .addComponent(bookingStatusDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(bookingStatusFindButton)))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Booking Status", jPanel3);

        waitlistStatusDayLabel.setText("Day:");

        waitlistStatusDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----select----" }));

        waitlistStatusFindButton.setText("Find");
        waitlistStatusFindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitlistStatusFindButtonActionPerformed(evt);
            }
        });

        waitlistStatusCustomersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Customers Waitlisted:" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(waitlistStatusCustomersList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(waitlistStatusDayLabel)
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waitlistStatusFindButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waitlistStatusDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(waitlistStatusDayLabel)
                            .addComponent(waitlistStatusDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(waitlistStatusFindButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Waitlist Status", jPanel4);

        addFlightNameLabel.setText("Flight Name:");

        addFlightSeatsLabel.setText("Seats:");

        addFlightButton.setText("Add Flight");
        addFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightButtonActionPerformed(evt);
            }
        });

        addFlightStatusLabel.setText("Status:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addFlightStatusLabel)
                    .addComponent(addFlightNameLabel)
                    .addComponent(addFlightSeatsLabel))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addFlightSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFlightNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFlightButton))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFlightNameLabel)
                    .addComponent(addFlightNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFlightSeatsLabel)
                    .addComponent(addFlightSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(addFlightButton)
                .addGap(30, 30, 30)
                .addComponent(addFlightStatusLabel)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Flight", jPanel5);

        cancelCustomerNameLabel.setText("Customer:");

        cancelCustomerDayLabel.setText("Day:");

        cancelCustomerButton.setText("Cancel Customer");
        cancelCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelCustomerDayLabel)
                    .addComponent(cancelCustomerNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelCustomerButton)
                    .addComponent(cancelCustomerNameComboBox, 0, 222, Short.MAX_VALUE)
                    .addComponent(cancelCustomerDayComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelCustomerNameLabel)
                    .addComponent(cancelCustomerNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelCustomerDayLabel)
                    .addComponent(cancelCustomerDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(cancelCustomerButton)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cancel Customer", jPanel6);

        addDayLabel.setText("Day:");

        addDateSpinner.setModel(new javax.swing.SpinnerDateModel());

        addDateButton.setText("Add Date");
        addDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateButtonActionPerformed(evt);
            }
        });

        addDayStatusLabel.setText("Status:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addDayStatusLabel)
                    .addComponent(addDayLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDateButton)
                    .addComponent(addDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(463, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDayLabel)
                    .addComponent(addDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addDateButton)
                .addGap(18, 18, 18)
                .addComponent(addDayStatusLabel)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Day", jPanel7);

        customerStatusLabel.setText("Customer:");

        customerStatusButton.setText("Status");
        customerStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerStatusButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(customerStausList1);

        jScrollPane4.setViewportView(customerStausList2);

        jLabel1.setText("Booked:");

        jLabel2.setText("Waitlisted:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(customerStatusLabel)
                        .addGap(18, 18, 18)
                        .addComponent(customerStausComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(customerStatusButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerStatusLabel)
                    .addComponent(customerStausComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(customerStatusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(68, 68, 68))))
        );

        jTabbedPane1.addTab("Customer Status", jPanel8);

        dropFlightLabel.setText("Flight:");

        dropFlightButton.setText("Drop");
        dropFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropFlightButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(dropFlightLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dropFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(dropFlightButton)))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropFlightLabel)
                    .addComponent(dropFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(dropFlightButton)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Drop Flight", jPanel9);

        title.setBackground(new java.awt.Color(51, 51, 51));
        title.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(0, 51, 255));
        title.setText("Flight Scheduler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        // TODO add your handling code here:
        Passenger passenger = new Passenger();
        String str = customerNameTextField.getText();
        int result = passenger.addPassenger(str);
        if(result!=0)
        {
            addCustomerStatusLabel.setText("Status: Passeenger added to database!");
        }
        else
        {
            addCustomerStatusLabel.setText("Status: Passenger not added to database, error occured");
        }
        customerNameTextField.setText("");
        try {
            updatePassengerComboBoxes();
        } catch (SQLException ex) {
            Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // TODO add your handling code here:
        Passenger name = (Passenger)bookCustomerComboBox.getSelectedItem();
        Flight flightName = (Flight)bookFlightComboBox.getSelectedItem();
        int result = 0;
        Day day = (Day)bookDayComboBox.getSelectedItem();
        Booking booking = new Booking();
        Waitlist waitlist = new Waitlist();
        int seatsBooked = booking.getSeatsBooked(flightName.toString(),day.toDate());
        
        Flight flight = new Flight();
        int seatsAvailable = flight.getSeatsAvailable(flightName.toString());
        if(seatsAvailable>seatsBooked)
        {
            result = booking.addBooking(name.toString(), flightName.toString(), day.toDate());
            if(result!=0)
            {
                bookCustomerStatusLabel.setText("Status: Flight successfully booked!");
            }
            else
            {
                bookCustomerStatusLabel.setText("Status: Error, Flight not booked!");
            }
        }
        else
        {
            result = waitlist.addBooking(name.toString(), flightName.toString(), day.toDate());
            if(result!=0)
            {
                bookCustomerStatusLabel.setText("Status: Flight full.. But you're waitlisted at position "+result+ "!!");
            }
            else
            {
                bookCustomerStatusLabel.setText("Status: Error, Flight not booked/waitlisted!");
            }
        }
        
    }//GEN-LAST:event_bookButtonActionPerformed

    private void bookingStatusFindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingStatusFindButtonActionPerformed
        // TODO add your handling code here:
        Flight flightName = (Flight)bookFlightComboBox.getSelectedItem();
        Day day = (Day)bookDayComboBox.getSelectedItem();
        List<Booking> b=null;
        try {
            b = Booking.getCustomersBooked(flightName.toString(), day.toDate());
        } catch (SQLException ex) {
            Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
        }
        Booking[] a= b.toArray(new Booking[b.size()]);
        
        DefaultListModel<String> model = new DefaultListModel<String>();
    for(Booking p : a){
        model.addElement(p.ToString1());
    }
        
        customersBookedList.setModel(model);
    }//GEN-LAST:event_bookingStatusFindButtonActionPerformed

    private void waitlistStatusFindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitlistStatusFindButtonActionPerformed
        // TODO add your handling code here:
        
        Day day = (Day)waitlistStatusDayComboBox.getSelectedItem();
        List<Waitlist> b=null;
        try {
            b = Waitlist.getCustomersBooked(day.toDate());
        } catch (SQLException ex) {
            Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
        }
        Waitlist[] a= b.toArray(new Waitlist[b.size()]);
        
        DefaultListModel<String> model = new DefaultListModel<String>();
    for(Waitlist p : a){
        model.addElement(p.ToString1());
    }
        
        waitlistStatusCustomersList.setModel(model);
    }//GEN-LAST:event_waitlistStatusFindButtonActionPerformed

    private void addFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightButtonActionPerformed
        // TODO add your handling code here:
        Flight flight = new Flight();
        String flightName = addFlightNameTextField.getText();
        int seats = Integer.parseInt(addFlightSeatsTextField.getText());
        int result = flight.addFlight(flightName,seats);
        if(result!=0)
        {
            addFlightStatusLabel.setText("Status: Flight added to database!");
        }
        else
        {
            addFlightStatusLabel.setText("Status: Flight not added to database. An error occured");
        }
        addFlightNameTextField.setText("");
        addFlightSeatsTextField.setText("");
        try {
            updateFlightComboBoxes();
        } catch (SQLException ex) {
            Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addFlightButtonActionPerformed

    private void cancelCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCustomerButtonActionPerformed
        // TODO add your handling code here:
        
        
        Passenger name = (Passenger)cancelCustomerNameComboBox.getSelectedItem();
        Day day = (Day)cancelCustomerDayComboBox.getSelectedItem();
        
        
        // delete customer from bookings
        List<Booking> b=null;
        try {
            b = Booking.getCustomerDayBooked(name.toString(), day.toDate());
        } catch (SQLException ex) {
            Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
        }
        Booking[] a= b.toArray(new Booking[b.size()]);
        Booking booking = new Booking();
        
        for(Booking p : a)
        {
            try {
                //deletes the booking
                
                booking.deleteBookingRecord(p.getPassenger(), p.getFlightNumber(), p.getDay());
                int seatsBooked = booking.getSeatsBooked(p.getFlightNumber(),p.getDay());
                Flight flight = new Flight();
                int seatsAvailable = flight.getSeatsAvailable(p.getFlightNumber());
                
                //checks if new entry can be added from waitlist
                if(seatsAvailable>seatsBooked)
                {
                        Waitlist x= new Waitlist();
                        String newName = x.getFirstWaitList(p.getFlightNumber(), p.getDay());
                        booking.addBooking(newName, p.getFlightNumber(), p.getDay());
                }
            } catch (SQLException ex) {
                Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        //delete booking from waitlist
        List<Waitlist> w=null;
        try {
            w = Waitlist.getCustomerDayWaitlisted(name.toString(), day.toDate());
        } catch (SQLException ex) {
            Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
        }
        Waitlist[] h= w.toArray(new Waitlist[w.size()]);
        Waitlist waitlist = new Waitlist();
        
        for(Waitlist p : h)
        {
            try {
                waitlist.deleteWaitlistRecord(p.getPassenger(), p.getFlightNumber(), p.getDay());
                waitlist.updateWaitlistPositions(p.getFlightNumber(), p.getDay(),p.getPosition());
            } catch (SQLException ex) {
                Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_cancelCustomerButtonActionPerformed

    private void addDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateButtonActionPerformed
        // TODO add your handling code here:
        
        SimpleDateFormat formater = new SimpleDateFormat("yyyy/MM/dd"); 
        String spinnerValue = formater.format(addDateSpinner.getValue()); 
        java.util.Date aday=null;
        try {
            aday = new SimpleDateFormat("yyyy/MM/dd").parse(spinnerValue);
        } catch (ParseException ex) {
            Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.sql.Date day = new java.sql.Date(aday.getTime());  
        Day date = new Day();
        int result = date.addDay(day);
        if(result!=0)
        {
            addDayStatusLabel.setText("Status: Day added to database!");
        }
        else
        {
            addDayStatusLabel.setText("Status: Day not added to database. An error occured");
        }
        try {
            updatePassengerComboBoxes();
        } catch (SQLException ex) {
            Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            updateDayComboBoxes();
        } catch (SQLException ex) {
            Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addDateButtonActionPerformed

    private void customerStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerStatusButtonActionPerformed
        // TODO add your handling code here:
        Passenger passenger = (Passenger)customerStausComboBox.getSelectedItem();
        List<Waitlist> p=null;
        List<Booking> q = null;
        try {
            p = Waitlist.getCustomersBooked(passenger.getPassenger());
        } catch (SQLException ex) {
            Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
        }
        Waitlist[] a= p.toArray(new Waitlist[p.size()]);
        
        DefaultListModel<String> model = new DefaultListModel<String>();
    for(Waitlist i : a){
        model.addElement(i.ToString1());
    }
    customerStausList1.setModel(model);
    
    
    try {
            q = Booking.getCustomersBooked(passenger.getPassenger());
        } catch (SQLException ex) {
            Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
        }
        Booking[] c= q.toArray(new Booking[q.size()]);
        
        DefaultListModel<String> model1 = new DefaultListModel<String>();
    for(Booking i : c){
        model1.addElement(i.ToString1());
    }
    customerStausList2.setModel(model1);
    
    }//GEN-LAST:event_customerStatusButtonActionPerformed

    private void dropFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropFlightButtonActionPerformed
        // TODO add your handling code here:
        
        
        
        // REMOVE FLIGHT FROM THE APPLICATION
        Flight flight = (Flight)dropFlightComboBox.getSelectedItem();
        Flight f= new Flight();
        try {
            f.deleteFlightRecord(flight.toString());
        } catch (SQLException ex) {
            Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            updateFlightComboBoxes();
        } catch (SQLException ex) {
            Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        //CUSTOMERS IN WAITLIST DELETED
        
        Waitlist w= new Waitlist();
        try {
            w.deleteWaitlistRecord(flight.toString());
        } catch (SQLException ex) {
            Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_dropFlightButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FlightScheduler().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FlightScheduler.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void updatePassengerComboBoxes() throws SQLException
    {
        DefaultComboBoxModel defaultCustomerModel = new DefaultComboBoxModel(Passenger.getAllPassenger().toArray());
        bookCustomerComboBox.setModel(defaultCustomerModel);
        cancelCustomerNameComboBox.setModel(defaultCustomerModel);
        customerStausComboBox.setModel(defaultCustomerModel);
    }
    
    public void updateFlightComboBoxes() throws SQLException
    {
        DefaultComboBoxModel defaultCustomerModel = new DefaultComboBoxModel(Flight.getAllFlights().toArray());
        bookFlightComboBox.setModel(defaultCustomerModel);
        bookingStatusFlightComboBox.setModel(defaultCustomerModel);
        dropFlightComboBox.setModel(defaultCustomerModel);
    }
    
    public void updateDayComboBoxes() throws SQLException
    {
        DefaultComboBoxModel defaultCustomerModel = new DefaultComboBoxModel(Day.getAllDays().toArray());
        bookDayComboBox.setModel(defaultCustomerModel);
        bookingStatusDayComboBox.setModel(defaultCustomerModel);
        waitlistStatusDayComboBox.setModel(defaultCustomerModel);
        cancelCustomerDayComboBox.setModel(defaultCustomerModel);
    }
    
    private Passenger currentEntry=null;
    private Passenger passengerQueries=new Passenger();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JLabel addCustomerStatusLabel;
    private javax.swing.JButton addDateButton;
    private javax.swing.JSpinner addDateSpinner;
    private javax.swing.JLabel addDayLabel;
    private javax.swing.JLabel addDayStatusLabel;
    private javax.swing.JButton addFlightButton;
    private javax.swing.JLabel addFlightNameLabel;
    private javax.swing.JTextField addFlightNameTextField;
    private javax.swing.JLabel addFlightSeatsLabel;
    private javax.swing.JTextField addFlightSeatsTextField;
    private javax.swing.JLabel addFlightStatusLabel;
    private javax.swing.JButton bookButton;
    private javax.swing.JComboBox<String> bookCustomerComboBox;
    private javax.swing.JLabel bookCustomerLabel;
    private javax.swing.JLabel bookCustomerStatusLabel;
    private javax.swing.JComboBox<String> bookDayComboBox;
    private javax.swing.JLabel bookDayLabel;
    private javax.swing.JComboBox<String> bookFlightComboBox;
    private javax.swing.JLabel bookFlightLabel;
    private javax.swing.JComboBox<String> bookingStatusDayComboBox;
    private javax.swing.JLabel bookingStatusDayLabel;
    private javax.swing.JButton bookingStatusFindButton;
    private javax.swing.JComboBox<String> bookingStatusFlightComboBox;
    private javax.swing.JLabel bookingStatusFlightLabel;
    private javax.swing.JButton cancelCustomerButton;
    private javax.swing.JComboBox<String> cancelCustomerDayComboBox;
    private javax.swing.JLabel cancelCustomerDayLabel;
    private javax.swing.JComboBox<String> cancelCustomerNameComboBox;
    private javax.swing.JLabel cancelCustomerNameLabel;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JButton customerStatusButton;
    private javax.swing.JLabel customerStatusLabel;
    private javax.swing.JComboBox<String> customerStausComboBox;
    private javax.swing.JList<String> customerStausList1;
    private javax.swing.JList<String> customerStausList2;
    private javax.swing.JList<String> customersBookedList;
    private javax.swing.JButton dropFlightButton;
    private javax.swing.JComboBox<String> dropFlightComboBox;
    private javax.swing.JLabel dropFlightLabel;
    private javax.swing.JLabel enterCustomerNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel title;
    private javax.swing.JList<String> waitlistStatusCustomersList;
    private javax.swing.JComboBox<String> waitlistStatusDayComboBox;
    private javax.swing.JLabel waitlistStatusDayLabel;
    private javax.swing.JButton waitlistStatusFindButton;
    // End of variables declaration//GEN-END:variables

}
